[package]
name = "imcrop"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
regex = "1.5.4"
clap = "2.33"

[profile.release]
opt-level = 'z'
lto = true
strip = true